### ISSUE TITLE
no data

### ISSUE THREAD

**Issue by daro1337** [szimszon/backuppc_monitor_zabbix#2]
Hey, i'm forcing issue with your backuppc template. I tried to solve it but i have no idea what wrong.
I did everything from istruction, and discovery seems to work it found my 2 hosts from backuppc, but thats all, i dont have any data.
output from sudo -u backuppc /usr/local/bin/zabbix-backuppc.pl is 1
output from sudo -u backuppc /usr/local/bin/zabbix-discover-backuppc.pl
{  "data":[
    {"{#BACKUPHOST}":"localhost"}
,    {"{#BACKUPHOST}":"10.199.0.34"}
  ]}
I'm at ubuntu 14lts backuppc from repo, zabbix 2.4
maybe you can tell me how to find issue, so i can fix it by myself:)
Thanks in advance

**Comment by szimszon** [comment]
Hi,

Please look at your zabbix host config:
Configuration -> Hosts -> In the list click on the Discovery in the host's row and please take a look at the end of the

Template_App_BackupPC: Discover backup hosts

line. If the discovery isn't working with the zabbix server you will see a red X. If you hover the mouse over the X you will see some hint about the problem.

The zabbix-backuppc.pl script output only 1. Because it is just a trigger to do data collection. So zabbix server run it but the script sends data with zabbix-sender. You can't see it in the console. You can run tcpdump to check network traffic...

**Comment by daro1337** [comment]
thank you for reply, I noticed now that there is error, "Value should be a JSON object." I have not seen this previously…

**Comment by szimszon** [comment]
In a console please su to zabbix and than try to run sudo -u....

Also check the sudoers file.

**Comment by daro1337** [comment]
ok, i mess with sudoers file, now i dont have this error.  But still i dont have data:(  Do i have to add any interface in Host tab? I have "Agent interfaces 127.0.0.1 : 10050" I think i'm so close to solve this..

**Comment by szimszon** [comment]
Please check if you have a

BackupPC - Collect Data

item with a value 1.
If you don't have it then that means /usr/local/bin/zabbix-backuppc.pl doesn't run. You should check it to run it as user zabbix too. I mean with sudo -u backuppc...

Another thing if discovery works you should have many item already. In Latest data you can check the Show items without data:    and look at it.

**Comment by daro1337** [comment]
I didnt have BackupPC - Collect Data item with a value 1. So I was thinking whole night about this issue and i figure it out:). Because I have to manage two zabbix servers  I've changed Hostname in zabbix frontends like "Zabbix Server 1" and "Zabbix Server 2"  I didnt change the name in "/etc/zabbix/zabbix_agentd.conf" from default Hostname=Zabbix server to e.g Hostname="Zabbix server 1" after this change, and restart zabbix agent  everything is working :) Thank you for your help:)

**Comment by szimszon** [comment]
You are welcome!
